---
- name: restart mariadb
  ansible.builtin.service:
    name: mariadb
    state: restarted

- name: restart snmpd
  ansible.builtin.service:
    name: snmpd
    state: restarted
  failed_when: false
