---
- name: Configuración común para todos los servidores
  hosts: all
  become: yes
  roles:
    - common

- name: Configurar servidor DNS
  hosts: dns
  become: yes
  roles:
    - dns

- name: Configurar servidor LDAP
  hosts: ldap
  become: yes
  roles:
    - ldap

- name: Configurar servidor de base de datos
  hosts: database
  become: yes
  roles:
    - database

- name: Configurar servidor web
  hosts: webserver
  become: yes
  roles:
    - webserver
    - webmail

- name: Configurar servidor de correo
  hosts: mail
  become: yes
  roles:
    - mail
